### ISSUE TITLE
Gnome 42 on Ubuntu 22.04

### ISSUE THREAD

**Issue by verndog** [ewlsh/dynamic-panel-transparency#154]
Top Panel transparency not working

**Comment by Batwam** [comment]
because it's marked as not compatible or you installed it anyway and it doesn't work? For info, I noticed that the Blur my Shell extension does happen to make the top bar transparent so that might be a good temporary solution for you (actually transparent with blur by default but you can also go into Panel -> Customize Properties -> Sigma and set as 0 if you want full transparency): https://extensions.gnome.org/extension/3193/blur-my-shell/

**Comment by johanla0** [comment]
I'd rather say it conflicts with the other extensions, for instance 'Blur my Shell' (even if the last one has disabled settings for the top panel).
